# Generated by Django 4.0.4 on 2022-04-11 18:28

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=posts.models.upload_image_banners)),
                ('ativo', models.BooleanField(default=False)),
                ('data_postagem', models.DateField()),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('texto', models.TextField(blank=True, null=True, verbose_name='texto')),
                ('url_post', models.CharField(blank=True, max_length=150, null=True, verbose_name='url')),
            ],
            options={
                'db_table': 'tb_banner',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(choices=[('Alimentação', 'Alimentação'), ('Terapia', 'Terapia')], max_length=100)),
            ],
            options={
                'db_table': 'tb_categoria',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('imagem', models.ImageField(upload_to=posts.models.upload_image_posts)),
                ('data_cadastro', models.DateField()),
                ('ativo', models.BooleanField(default=False)),
                ('data_postagem', models.DateField(blank=True, null=True)),
                ('texto', models.TextField(verbose_name='texto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='posts.categoria')),
            ],
            options={
                'db_table': 'tb_post',
                'ordering': ('id',),
            },
        ),
    ]
