# Generated by Django 4.0.4 on 2022-04-11 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user_cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cadastro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='user_postagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(1), related_name='user_postagem', to=settings.AUTH_USER_MODEL),
        ),
    ]
